name = "DataStreams"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
WeakRefStrings = "â‰¥ 0.4.0"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test"]
